### ISSUE TITLE
Crash when running from child fragment

### ISSUE THREAD

**Issue by hrach** [afollestad/assent#9]
**Library Version:**

2.2.3
 
**Affected Device(s):**
 
Google Pixel 2 with Android Q
 
**To Reproduce:**
1. If I call `runWithPermissions` from fragment which is attached to `childFragmentManager` an exception is thrown:

```
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65616, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {XXX/XXXui.activity.main.MainActivity}: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment PermissionFragment{9bdf753 (79540633-3812-4049-a38b-e4b0f34675f7) [assent_permission_fragment/fragment]} is already attached to a FragmentManager.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4618)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4660)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment PermissionFragment{9bdf753 (79540633-3812-4049-a38b-e4b0f34675f7) [assent_permission_fragment/fragment]} is already attached to a FragmentManager.
        at androidx.fragment.app.BackStackRecord.detach(BackStackRecord.java:355)
        at com.afollestad.assent.internal.PermissionFragment$detach$1.invoke(PermissionFragment.kt:38)
        at com.afollestad.assent.internal.PermissionFragment$detach$1.invoke(PermissionFragment.kt:27)
        at com.afollestad.assent.internal.ExtensionsKt.transact(Extensions.kt:85)
        at com.afollestad.assent.internal.PermissionFragment.detach$library_release(PermissionFragment.kt:37)
        at com.afollestad.assent.internal.Data$Companion.forgetFragment(Data.kt:77)
        at com.afollestad.assent.internal.PermissionFragmentKt.onPermissionsResponse(PermissionFragment.kt:101)
        at com.afollestad.assent.internal.PermissionFragment.onRequestPermissionsResult(PermissionFragment.kt:57)
        at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:750)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8110)
        at android.app.Activity.dispatchActivityResult(Activity.java:7960)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4611)
```

**Expected Behavior:**

no crash

**Comment by afollestad** [comment]
Huh, I'm having trouble reproducing this

**Comment by CarsonRedeye** [comment]
I'm also getting this crash. When I run `runWithPermissions` from a Fragment inside a Fragment pager adapter

**Comment by CarsonRedeye** [comment]
On further investigation it only happens when I upgrade to navigation components 2.1.0-alpha02. This uses the androidx fragments which must cause this bug

**Comment by afollestad** [comment]
I use AndroidX Fragments and have not observed any problems.

**Comment by CarsonRedeye** [comment]
Which version? Some of these bugs might be causing the problem. Navigation components currently only depends on `androidx.fragment:fragment:1.1.0-alpha05` maybe they fixed it in alpha06 or 07. Could you test with alpha05?

**Comment by CarsonRedeye** [comment]
To further clarify, Navigation version 1.0.0 works, but Navigation 2.1.0-alpha02 doesn't

**Comment by afollestad** [comment]
I meant specifically indidual AndroidX Fragments (`androidx.app.Fragment`), not the dependency there or anything navigation related.

**Comment by CarsonRedeye** [comment]
Sorry if I wasn't clear. I'm talking about the `androidx.app.Fragment` also. It has different versions released via jetpack now. I only mentioned Navigation because it internally depends on different versions of fragment. I've narrowed the crash down to happening if you depend on  `"androidx.fragment:fragment:1.1.0-alpha05"` (or `alpha06` or `alpha07`) but it doesn't happen if you depend on implementation `"androidx.fragment:fragment:1.1.0-alpha04"`.

**Comment by CarsonRedeye** [comment]
Does any of this sounds suspiscious ? https://developer.android.com/jetpack/androidx/releases/fragment#1.1.0-alpha05

**Comment by CarsonRedeye** [comment]
So the crash is obviously related to the change in fragment `alpha05`
"Calling remove(), hide(), show(), detach(), and setPrimaryNavigationFragment() with a Fragment attached to a different FragmentManager now throws an IllegalStateException rather than silently failing (aosp/904301)"
I had a look at your code to see if I could make a PR but couldn't see the solution. Looking forward to a fix. Cheers

**Comment by guger** [comment]
I'm getting the same error when calling it from within a `DialogFragment`.

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65596, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {at.guger.moneybook.dev/at.guger.moneybook.ui.activity.MainActivity}: java.lang.IllegalStateException: Cannot detach Fragment attached to a different FragmentManager. Fragment PermissionFragment{e597fd5 (a8933ae6-618e-41cd-be92-64617c72530a) [assent_permission_fragment/fragment]} is already attached to a FragmentManager.
```

I'm using AndroidX libraries:
Navigation: 2.1.0-alpha03
Fragment: 1.1.0-alpha08

**Comment by afollestad** [comment]
I think the fix to https://github.com/afollestad/assent/issues/13 should fix this as well, let me know if not (release coming soon)

**Comment by CarsonRedeye** [comment]
Yeah works for me!
